Update room, sqlite version
Was getting the following crash when running on Samsung Watch 4

```
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__atomic_store_4" referenced by "/data/app/~~2lfcXKNtWFnzLw7cskZAcQ==/com.ramitsuri.notificationjournal.debug-JLbSEB_VBGJNGl-kJPiftw==/base.apk!/lib/armeabi-v7a/libsqliteJni.so"...
                                                                                        	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
                                                                                        	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
                                                                                        	at java.lang.System.loadLibrary(System.java:1661)
                                                                                        	at androidx.sqlite.driver.bundled.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.android.kt:24)
                                                                                        	at androidx.sqlite.driver.bundled.BundledSQLiteDriver.<clinit>(BundledSQLiteDriver.androidJvmCommon.kt:36)
```

It seems from the fix changelog for library, it was on Samsung because
it's ARM 32 and emulator is ARM 64 which is why ran fine.